steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/emubench-serv', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/emubench-serv']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'emubench-serv'
      - '--image'
      - 'gcr.io/$PROJECT_ID/emubench-serv'
      - '--region'
      - 'us-central1'

# Specify the service account for Cloud Build
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/emubench-cloud-build-sa@$PROJECT_ID.iam.gserviceaccount.com'

# Configure logging to use Cloud Logging only
options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/emubench-serv'
